- name: BigData擬似分散モード
  hosts: localhost
  connection: local
  tasks:
    # ========================================================
    # yum common install
    # ========================================================
    - name: wgetインストール
      yum:  name=wget
    - name: lsofインストール
      yum:  name=lsof
    - name: gitインストール
      yum:  name=git
    # ========================================================
    # Java
    # ========================================================
    - name: javaの存在確認
      shell: which java
      register: java_which
      failed_when: java_which.rc not in [0, 1]
    - name: Javaインストール
      yum: name=java-1.8.0-openjdk-devel
      when: java_which.rc == 1
    # ========================================================
    # nginx
    # ========================================================
    - name: nginxインストール
      yum:  name=templates/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    - name: nginx yum
      yum:  name=nginx
    # ========================================================
    # CDH
    # ========================================================
    - name: rpmを貼る
      yum: name=templates/cloudera-cdh-5-0.x86_64.rpm
    - name: hadoop-conf-pseudoインストール
      yum: name=hadoop-conf-pseudo
    # ========================================================
    # HBase
    # ========================================================
    - name: Hbaseインストール
      yum:  name=hbase-master
    # ========================================================
    # 初期化 起動時のセット
    # ========================================================
    - name: hdfsをフォーマット
      shell: sudo -u hdfs hdfs namenode -format
    - name: hdfs start
      shell: for x in `cd /etc/init.d ; ls hadoop-hdfs-*` ; do sudo service $x start ; done
    - name: hdfsを初期化
      shell: sudo /usr/lib/hadoop/libexec/init-hdfs.sh
    - name: set auto start nginx
      command: chkconfig nginx on
    - name: set auto start hadoop-yarn-resourcemanager
      command: chkconfig hadoop-yarn-resourcemanager on
    - name: set auto start hadoop-yarn-nodemanager
      command: chkconfig hadoop-yarn-nodemanager on
    - name: set auto start hadoop-mapreduce-historyserver
      command: chkconfig hadoop-mapreduce-historyserver on
    # ========================================================
    # restart
    # ========================================================
    - name: restart nginx
      command: service nginx restart
    - name: restart hadoop-yarn-resourcemanager
      command: service hadoop-yarn-resourcemanager restart
    - name: restart hadoop-yarn-nodemanager
      command: service hadoop-yarn-nodemanager restart
    - name: restart hadoop-mapreduce-historyserver
      command: service hadoop-mapreduce-historyserver restart
    # ========================================================
    # HBase
    # ========================================================
    - name: Hbaseインストール
      yum:  name=hbase-master
    - name: set auto start hbase-master
      command: chkconfig hbase-master on
    - name: restart hbase-master
      command: service hbase-master restart
