- name: BigData環境構築
  hosts: localhost
  connection: local
  tasks:
    # ========================================================
    # yum install
    # ========================================================
    - name: wgetインストール
      yum:  name=wget
    - name: gitインストール
      yum:  name=git

    # ========================================================
    # Javaのインストール
    # ========================================================
    - name: javaの存在確認
      shell: which java
      register: java_which
      failed_when: java_which.rc not in [0, 1]

    - name: Java インストール
      yum: name=java-1.8.0-openjdk-devel
      when: java_which.rc == 1
    # ========================================================
    # Hadoopのインストール
    # ========================================================
    - name: Hdoopダウンロード
      get_url: url=" http://ftp.jaist.ac.jp/pub/apache/hadoop/common/hadoop-2.8.2/hadoop-2.8.2.tar.gz" dest=/tmp
    - unarchive: src=/tmp/hadoop-2.8.2.tar.gz dest=/usr/local/lib

    # ========================================================
    # HBaseのインストール
    # ========================================================
    - name: Hbaseダウンロード
      get_url: url="http://ftp.jaist.ac.jp/pub/apache/hbase/1.3.1/hbase-1.3.1-bin.tar.gz" dest=/tmp
    - unarchive: src=/tmp/hbase-1.3.1-bin.tar.gz dest=/usr/local/lib

    # ========================================================
    # テンプレート追加
    # ========================================================
    - template: src=templates/.bash_profile dest=~/.bash_profile owner=bin group=wheel mode=0644

