- name: BigData擬似分散モード
  hosts: localhost
  connection: local
  tasks:
    # ========================================================
    # yum install
    # ========================================================
    - name: wgetインストール
      yum:  name=wget
    - name: gitインストール
      yum:  name=git
    # ========================================================
    # Javaのインストール
    # ========================================================
    - name: javaの存在確認
      shell: which java
      register: java_which
      failed_when: java_which.rc not in [0, 1]

    - name: Javaインストール
      yum: name=java-1.8.0-openjdk-devel
      when: java_which.rc == 1
    # ========================================================
    # CDHインストール
    # ========================================================
    - name: CDHのrpmを貼る
      yum: templates/cloudera-cdh-5-0.x86_64.rpm
    - name: hadoop-conf-pseudoインストール
      yum: name=hadoop-conf-pseudo
    - name: hadoop-conf-pseudoインストール
      service: name=httpd state=started

#
#    # ========================================================
#    # HBaseのインストール
#    # ========================================================
#    - name: Hbaseダウンロード
#      get_url: url="http://ftp.jaist.ac.jp/pub/apache/hbase/1.3.1/hbase-1.3.1-bin.tar.gz" dest=/tmp
#    - unarchive: src=/tmp/hbase-1.3.1-bin.tar.gz dest=/usr/local/lib
#
#    # ========================================================
#    # テンプレート追加
#    # ========================================================
#    - name: bash_profile書き換え
#      template: src=templates/.bash_profile dest=/home/ishizukyousuke/.bash_profile owner=bin group=wheel mode=0644

