- name: wiki環境
  hosts: localhost
  connection: local
  tasks:
    # ========================================================
    # yum common install
    # ========================================================
    - name: wgetインストール
      yum:  name=wget
    - name: lsofインストール
      yum:  name=lsof
    - name: gitインストール
      yum:  name=git
    # ========================================================
    # nginx
    # ========================================================
    - name: nginxインストール
      yum:  name=templates/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    - name: nginx yum
      yum:  name=nginx
    # ========================================================
    # php
    # ========================================================
    - name: rpmを貼る
      yum:  name=templates/remi-release-7.rpm
    - name: PHPインストール
      yum: name=remi-php70 php70-php-fpm
    - name: set auto start nginx
      command: chkconfig nginx on
    - name: set auto start php-fpm
      command: chkconfig php-fpm on
    - name: rchkconfignginx
      command: service nginx restart
    - name: rchkconfig php-fpm on
      command: service php-fpm restart